#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SRU
version:      0.3
version_from: lib/SRU.pm
installdirs:  site
requires:
    XML::LibXML:                   
    Class::Accessor:               
    URI:                           

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
