# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SRU
version:      0.92
version_from: lib/SRU.pm
installdirs:  site
requires:
    CGI::Application:              
    Class::Accessor:               
    CQL::Parser:                   0.3
    Test::Exception:               
    URI:                           
    XML::LibXML:                   
    XML::Simple:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
