---
abstract: 'Search and Retrieval by URL'
author:
  - 'Ed Summers <ehs@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SRU
no_index:
  directory:
    - inc
    - t
requires:
  CQL::Parser: 0.3
  Class::Accessor: 0
  URI: 0
  XML::LibXML: 0
  XML::Simple: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/edsu/sru-perl/tree/master
version: 0.98
