--- #YAML:1.0
name:                SRU
version:             0.96
abstract:            Search and Retrieve URL Service
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::Accessor:               
    CQL::Parser:                   0.3
    Test::Exception:               
    URI:                           
    XML::LibXML:                   
    XML::Simple:                   
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ed Summers <ehs@pobox.com>
