#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SRU
version:      0.5
version_from: lib/SRU.pm
installdirs:  site
requires:
    CGI::Application:              
    URI:                           
    CQL::Parser:                   
    Class::Accessor:               
    XML::LibXML:                   
    XML::Simple:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
