#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SRU
version:      0.1
version_from: lib/SRU/Request.pm
installdirs:  site
requires:
    URI:                           
    XML::LibXML:                   
    Class::Accessor:               

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
