#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SRU
version:      0.6
version_from: lib/SRU.pm
installdirs:  site
requires:
    CQL::Parser:                   0.3
    XML::Simple:                   
    URI:                           
    CGI::Application:              
    XML::LibXML:                   
    Class::Accessor:               

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
